// Code generated by tygo. DO NOT EDIT.

//////////
// source: protocol.go
/*
Package protocol defines the WebSocket wire contract between hayduk and
the browser. Field names and JSON tags are frozen; the TypeScript types in
ui/src/protocol/types.ts are generated from this file and must not drift.
*/

/**
 * Wire message kinds.
 */
export const KindHello = "hello";
/**
 * Wire message kinds.
 */
export const KindSnapshot = "snapshot";
/**
 * Wire message kinds.
 */
export const KindResource = "resource";
/**
 * Wire message kinds.
 */
export const KindEvent = "event";
/**
 * Wire message kinds.
 */
export const KindSessionOutput = "sessionOutput";
/**
 * Wire message kinds.
 */
export const KindConsoleOutput = "consoleOutput";
/**
 * Wire message kinds.
 */
export const KindResponse = "response";
/**
 * Wire message kinds.
 */
export const KindCommand = "command";
/**
 * Resource names carried by resource updates.
 */
export const ResConnection = "connection";
/**
 * Resource names carried by resource updates.
 */
export const ResHosts = "hosts";
/**
 * Resource names carried by resource updates.
 */
export const ResServices = "services";
/**
 * Resource names carried by resource updates.
 */
export const ResSessions = "sessions";
/**
 * Resource names carried by resource updates.
 */
export const ResJobs = "jobs";
/**
 * Resource names carried by resource updates.
 */
export const ResCreds = "creds";
/**
 * Resource names carried by resource updates.
 */
export const ResLoot = "loot";
/**
 * Resource names carried by resource updates.
 */
export const ResModules = "modules";
/**
 * Resource names carried by resource updates.
 */
export const ResConsole = "console";
/**
 * Resource names carried by resource updates.
 */
export const ResInteract = "interact";
/**
 * Resource names carried by resource updates.
 */
export const ResRoutes = "routes";
/**
 * Resource names carried by resource updates.
 */
export const ResModuleRanks = "moduleRanks";
/**
 * Resource names carried by resource updates.
 */
export const ResOperators = "operators";
/**
 * Error codes.
 */
export const CodeUnknownMethod = "unknown_method";
/**
 * Error codes.
 */
export const CodeBadParams = "bad_params";
/**
 * Error codes.
 */
export const CodeNotConnected = "not_connected";
/**
 * Error codes.
 */
export const CodeBusy = "busy";
/**
 * Error codes.
 */
export const CodeConnectFailed = "connect_failed";
/**
 * Error codes.
 */
export const CodeSessionNotFound = "session_not_found";
/**
 * Error codes.
 */
export const CodeInvalidOption = "invalid_option";
/**
 * Error codes.
 */
export const CodeTimeout = "command_timeout";
/**
 * Error codes.
 */
export const CodeRPC = "rpc_error";
/**
 * Error codes.
 */
export const CodeUnexpected = "unexpected_response";
/**
 * Error codes.
 */
export const CodeInternal = "internal";
/**
 * Event levels.
 */
export const LevelInfo = "info";
/**
 * Event levels.
 */
export const LevelSuccess = "success";
/**
 * Event levels.
 */
export const LevelWarn = "warn";
/**
 * Event levels.
 */
export const LevelError = "error";
export const ProtoVersion = 1;
/**
 * ServerMessage is any server→client message value. The bus and server move
 * them as opaque payloads; marshaling happens at the socket.
 */
export type ServerMessage = any;
/**
 * Hello is the first message after the socket opens.
 */
export interface Hello {
  type: string;
  proto: number /* int */;
  version: string;
  team: boolean;
}
/**
 * Snapshot carries the full campaign state, sent on every (re)connect.
 */
export interface Snapshot {
  type: string;
  state: CampaignState;
}
/**
 * ConnectionState is one of the resources in CampaignState and also rides
 * the connect command response.
 */
export interface ConnectionState {
  status: string; // disconnected|connecting|connected|reconnecting
  host: string;
  port: number /* int */;
  ssl: boolean;
  username: string;
  msfVersion: string;
  workspace: string;
  error?: string;
}
export interface HostState {
  address: string;
  name: string;
  mac: string;
  osName: string;
  osFlavor: string;
  osVersion: string;
  purpose: string;
  info: string;
  comments: string;
}
export interface ServiceState {
  host: string;
  port: number /* int */;
  proto: string;
  name: string;
  state: string;
  info: string;
}
export interface SessionState {
  id: string;
  type: string; // meterpreter|shell
  tunnelPeer?: string;
  viaExploit?: string;
  viaPayload?: string;
  info?: string;
  username?: string;
  targetHost?: string;
  sessionHost?: string;
  uuid?: string;
  openedAt?: string;
}
export interface JobState {
  id: string;
  name: string;
  startedAt?: string;
}
/**
 * RouteState is one pivot route: a subnet reachable through a session.
 */
export interface RouteState {
  subnet: string;
  sessionId: string;
}
export interface CredState {
  host: string;
  port: number /* int */;
  proto: string;
  service: string;
  user: string;
  pass: string;
  type: string;
}
/**
 * LootState omits the loot data payload on purpose: it can be huge and the
 * table only needs identity and description.
 */
export interface LootState {
  host: string;
  type: string;
  name: string;
  info: string;
}
export interface ModuleIndex {
  exploits: string[];
  auxiliary: string[];
  post: string[];
  payloads: string[];
  encoders: string[];
  nops: string[];
  evasion: string[];
}
export interface ConsoleState {
  output: string;
}
export interface InteractState {
  sid: string;
  output: string;
}
export interface EventEntry {
  seq: number /* int64 */;
  time: string;
  level: string;
  text: string;
  operator?: string;
}
export interface CampaignState {
  connection: ConnectionState;
  hosts: (HostState | undefined)[];
  services: (ServiceState | undefined)[];
  sessions: { [key: string]: SessionState | undefined};
  jobs: { [key: string]: JobState | undefined};
  routes: (RouteState | undefined)[];
  creds: (CredState | undefined)[];
  loot: (LootState | undefined)[];
  modules?: ModuleIndex;
  moduleRanks: { [key: string]: string};
  console?: ConsoleState;
  interact?: InteractState;
  events: (EventEntry | undefined)[];
  operators: string[];
}
/**
 * ResourceUpdate refreshes one resource. Exactly the field matching Resource
 * is set; the rest stay nil and are omitted on the wire.
 */
export interface ResourceUpdate {
  type: string;
  resource: string;
  connection?: ConnectionState;
  hosts?: (HostState | undefined)[];
  services?: (ServiceState | undefined)[];
  sessions?: { [key: string]: SessionState | undefined};
  jobs?: { [key: string]: JobState | undefined};
  routes?: (RouteState | undefined)[];
  creds?: (CredState | undefined)[];
  loot?: (LootState | undefined)[];
  modules?: ModuleIndex;
  moduleRanks?: { [key: string]: string};
  console?: ConsoleState;
  interact?: InteractState;
  operators?: string[];
}
/**
 * EventMsg appends one entry to the operator-visible event log.
 */
export interface EventMsg {
  type: string;
  seq: number /* int64 */;
  time: string;
  level: string;
  text: string;
  operator?: string;
}
/**
 * SessionOutputMsg streams output of the attached session.
 */
export interface SessionOutputMsg {
  type: string;
  sid: string;
  data: string;
}
/**
 * ConsoleOutputMsg streams console output.
 */
export interface ConsoleOutputMsg {
  type: string;
  data: string;
}
/**
 * CommandResponse answers a client command; Data is set when OK.
 */
export interface CommandResponse {
  type: string;
  id: number /* int64 */;
  ok: boolean;
  data?: any /* json.RawMessage */;
  error?: ErrorBody;
}
export interface ErrorBody {
  code: string;
  message: string;
}
/**
 * ClientMessage is the only client→server message. Operator names the
 * acting operator in team mode.
 */
export interface ClientMessage {
  type: string;
  id: number /* int64 */;
  method: string;
  params?: any /* json.RawMessage */;
  operator?: string;
}
/**
 * Command methods.
 */
export const MethodConnect = "connect";
/**
 * Command methods.
 */
export const MethodDisconnect = "disconnect";
/**
 * Command methods.
 */
export const MethodConsoleWrite = "console.write";
/**
 * Command methods.
 */
export const MethodConsoleTabs = "console.tabs";
/**
 * Command methods.
 */
export const MethodModuleInfo = "module.info";
/**
 * Command methods.
 */
export const MethodModuleOptions = "module.options";
/**
 * Command methods.
 */
export const MethodPayloads = "module.compatible_payloads";
/**
 * Command methods.
 */
export const MethodModuleExecute = "module.execute";
/**
 * Command methods.
 */
export const MethodSessionAttach = "session.attach";
/**
 * Command methods.
 */
export const MethodSessionDetach = "session.detach";
/**
 * Command methods.
 */
export const MethodSessionWrite = "session.write";
/**
 * Command methods.
 */
export const MethodSessionStop = "session.stop";
/**
 * Command methods.
 */
export const MethodSessionUpgrade = "session.upgrade";
/**
 * Command methods.
 */
export const MethodWorkspaceList = "workspace.list";
/**
 * Command methods.
 */
export const MethodWorkspaceSet = "workspace.set";
/**
 * Command methods.
 */
export const MethodDBRefresh = "db.refresh";
/**
 * Command methods.
 */
export const MethodAttacksFind = "attacks.find";
/**
 * Command methods.
 */
export const MethodReportHTML = "report.html";
/**
 * Command methods.
 */
export const MethodHailMary = "campaign.hail_mary";
export interface ConnectParams {
  host: string;
  port: number /* int */;
  ssl: boolean;
  username: string;
  password: string;
}
export interface ConsoleWriteParams {
  command: string;
}
export interface ConsoleTabsParams {
  line: string;
}
export interface ModuleRefParams {
  type: string;
  name: string;
}
export interface ModuleExecuteParams {
  type: string;
  name: string;
  options: { [key: string]: any};
  payload?: string;
  payloadOptions?: { [key: string]: any};
}
export interface SessionRefParams {
  sid: string;
}
export interface SessionWriteParams {
  sid: string;
  data: string;
}
export interface SessionUpgradeParams {
  sid: string;
  lhost: string;
  lport: number /* int */;
}
export interface WorkspaceSetParams {
  name: string;
}
export interface AttacksFindParams {
  host: string;
}
export interface ReportPayload {
  html: string;
}
export interface HailMaryParams {
  hosts: string[];
  maxPerHost: number /* int */;
}
export interface HailMaryPayload {
  planned: number /* int */;
}
export interface ModuleInfoPayload {
  name: string;
  description: string;
  rank: string;
  authors: string[];
  references: ModuleRefPayload[];
  targets: string[];
  filePath: string;
}
export interface ModuleRefPayload {
  type: string;
  value: string;
}
export interface ModuleOptionPayload {
  type: string;
  required: boolean;
  advanced: boolean;
  desc: string;
  default: any;
  enums: string[];
}
export interface ExecPayload {
  jobId: number /* int */;
  uuid: string;
}
export interface AttackMatch {
  name: string;
  reason: string;
}
export interface AttacksPayload {
  host: string;
  matches: AttackMatch[];
}
