#!/bin/sh
# Rebuilds ui/src/styles/icons.css and the subset Phosphor fonts from the
# icons actually referenced in ui/src. Requires python3 with fonttools
# (pip install fonttools brotli). Run after adding new icons, then rebuild
# the UI (make ui).
set -e
cd "$(dirname "$0")/.."

python3 - << 'EOF'
import re
import subprocess
import sys
from pathlib import Path

root = Path(".")
src = root / "ui/src"
web = root / "ui/node_modules/@phosphor-icons/web/src"
out_css = src / "styles/icons.css"
out_fonts = src / "styles/fonts"
out_fonts.mkdir(parents=True, exist_ok=True)

# names referenced as ph-<name> classes anywhere in the source, plus any
# quoted string that is a real phosphor name - names built from data at
# runtime (menu items, tab tuples, ternaries) are only visible as literals,
# so over-inclusion is the safe direction
names = set()
for p in src.rglob("*"):
    if p.suffix not in (".ts", ".tsx", ".css"):
        continue
    text = p.read_text()
    names.update(re.findall(r"\bph-([a-z0-9-]+)", text))
    for m in re.finditer(r"([\"'])([a-z0-9][a-z0-9-]*)\1", text):
        names.add(m.group(2))
names -= {"fill", "bold", "thin", "light", "duotone"}  # weight classes
names = {n for n in names if not n.endswith("-")}  # template-literal partials
# dynamic template suffixes the scan cannot see
names |= {"folder-open"}

codepoints = {}
for weight, prefix in (("regular", "ph"), ("fill", "ph-fill")):
    css = (web / weight / "style.css").read_text()
    for name, cp in re.findall(r'\.%s\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)"' % prefix, css):
        codepoints.setdefault(name, {})[prefix] = cp

# literals that are not phosphor names are just strings (css classes, field
# names, numbers); only real glyph names ship
used = {}
for name in sorted(names):
    if name in codepoints:
        used[name] = codepoints[name]

def subset(weight, family, prefix):
    cps = sorted({cp for weights in used.values() for cp in [weights.get(prefix)] if cp})
    if not cps:
        return None
    src_font = web / weight / ("%s.woff2" % family)
    dst = out_fonts / ("phosphor-%s.woff2" % weight)
    subprocess.run([
        sys.executable, "-m", "fontTools.subset", str(src_font),
        "--output-file=%s" % dst, "--flavor=woff2",
        "--unicodes=%s" % ",".join("U+%s" % cp for cp in cps),
    ], check=True)
    return dst

regular = subset("regular", "Phosphor", "ph")
fill = subset("fill", "Phosphor-Fill", "ph-fill")

lines = ["/* Generated by scripts/subset-icons.sh - do not edit by hand. */"]
if regular:
    lines += [
        '@font-face {',
        '  font-family: "Phosphor";',
        '  src: url("./fonts/phosphor-regular.woff2") format("woff2");',
        '  font-weight: normal;',
        '  font-style: normal;',
        '  font-display: block;',
        '}',
    ]
if fill:
    lines += [
        '@font-face {',
        '  font-family: "Phosphor-Fill";',
        '  src: url("./fonts/phosphor-fill.woff2") format("woff2");',
        '  font-weight: normal;',
        '  font-style: normal;',
        '  font-display: block;',
        '}',
    ]
for family, prefix in (("Phosphor", "ph"), ("Phosphor-Fill", "ph-fill")):
    lines += [
        '.%s {' % prefix,
        '  font-family: "%s" !important;' % family,
        '  font-style: normal;',
        '  font-weight: normal;',
        '  font-variant: normal;',
        '  text-transform: none;',
        '  line-height: 1;',
        '  -webkit-font-smoothing: antialiased;',
        '  -moz-osx-font-smoothing: grayscale;',
        '}',
    ]
for name in sorted(used):
    if "ph" in used[name]:
        lines.append('.ph.ph-%s:before { content: "\\%s"; }' % (name, used[name]["ph"]))
    if "ph-fill" in used[name]:
        lines.append('.ph-fill.ph-%s:before { content: "\\%s"; }' % (name, used[name]["ph-fill"]))
out_css.write_text("\n".join(lines) + "\n")
print("%d icons -> %s" % (len(used), out_css))
EOF
